const partsCritical = [
  {text: "Generate a JSON object containing a practice question aimed at developing critical thinking skills for the National University Entrance Test (NUET). The question should present a complex scenario of at least 130 words, exploring diverse themes and requiring thoughtful analysis. Include diverse viewpoints and data to enhance the challenge. Emphasize logical reasoning, including drawing conclusions and identifying logical fallacies from data and arguments. Encourage examining situations from multiple perspectives for a nuanced understanding. Optionally, include an HTML table for data analysis, featuring high-level tasks. The output should be a single JSON object."},
  {text: ""},
];

const partsMath = [
  {text: "input: Goal: Create a comprehensive JSON file containing 30 unique and challenging math practice questions for the National University Entrance Test (NUET).Request: Generate an array named questions.Structure: Each element in the array should be a JSON object adhering to the specified format:\n\nEXAMPLE:\n[\n  {\n    \"id\": \"1\",\n    \"question\": \"If \\\\(\\\\ast\\\\) is a binary operation defined by \\\\(a \\\\ast b = a^2 + b^2 - ab\\\\), find the value of \\\\((2 \\\\ast 3) \\\\ast 4\\\\).\",\n    \"question_type\": \"binary operations\",\n    \"explanation\": \"First, find \\\\(2 \\\\ast 3 = 2^2 + 3^2 - (2)(3) = 7\\\\). Then, find \\\\((2 \\\\ast 3) \\\\ast 4 = 7 \\\\ast 4 = 7^2 + 4^2 - (7)(4) = 33\\\\).\",\n    \"options\": {\n      \"A\": \"13\",\n      \"B\": \"25\",\n      \"C\": \"33\",\n      \"D\": \"49\",\n      \"E\": null\n    },\n    \"correct_option\": \"C\",\n    \"svg_file\": null\n  },\n  {\n    \"id\": \"2\",\n    \"question\": \"Solve the inequality \\\\(3x - 5 < 2x + 4\\\\).\",\n    \"question_type\": \"inequality solving\",\n    \"explanation\": \"Subtract \\\\(2x\\\\) from both sides to get \\\\(x - 5 < 4\\\\). Then, add 5 to both sides to get \\\\(x < 9\\\\).\",\n    \"options\": {\n      \"A\": \"x > 9\",\n      \"B\": \"x < 9\",\n      \"C\": \"x = 9\",\n      \"D\": \"x \\\\leq 9\",\n      \"E\": null\n    },\n    \"correct_option\": \"B\",\n    \"svg_file\": null\n  }\n  // Add more questions as needed\n]\nEmphasis:Focus on open-ended scenarios that demand:Application of logical reasoning to draw conclusions and evaluate outcomes.Multi-perspective examination for a comprehensive understanding.Question Types:Cover classic NUET question formats, including:Binary operations and propertiesInequality solvingSimultaneous equationsAlgebraic fractions and manipulationExponents and logarithmsQuadratic equations and propertiesGeometric problems (separate process for SVG generation)Straight line equations and relationshipsLogic and reasoning with statementsWord problems involving volumes/surface areas (consider for challenge)Permutation and combination problems (consider for challenge)\n\nRETURN:\n\n\n\n{\n  \"id\": \"1\",  // Unique identifier for the question\n  \"question\": \"STRING\",  // Question text using better-react-mathjax markdown\n  \"questionType\": \"STRING\",  // Type of question, e.g., \"inequality solving\"\n  \"explanation\": \"STRING\",  // Explanation using better-react-mathjax markdown, if applicable\n  \"options\": [\n     \"STRING\",  // Option 1 text\n     \"STRING\",  // Option 2 text\n     \"STRING\",  // Option 3 text\n     \"STRING\",  // Option 4 text\n    \"STRING\"  // Optional, for 5-choice questions\n  ],\n  \"correct_option\": \"NUMBER\",  // NUMBER of the correct option, e.g., \"1\"\n  \"svg_file\": \"STRING\"  // Optional, path to the SVG file for geometric problems\n}"},
  {text: ""},
];


export {partsCritical, partsMath};

