export const questionTypesCritical = [
    "Which one of the following is an expression of the main conclusion of the above argument?",
    "Which one of the following is the best statement of the flaw in the above argument?",
    "Which one of the following is a conclusion that can reliably be drawn from the above passage?",
    "Which one of the following is an underlying assumption of the above argument?",
    "Which one of the following, if true, would most weaken the above argument?",
    "Which one of the following best identifies the flaw in the above reasoning?",
    "Which one of the following statements is not true?",
    "Which one of the following conclusions can reliably be drawn from the above passage?",
    "Which one of the following is an underlying assumption of the above argument?",
    "Which one of the following, if true, would most weaken the above argument?",
    "Which one of the following is the best expression of the flaw in the above argument?",
    "Which one of the following most closely parallels the reasoning used in the above argument?",
    "Which one of the following identifies the principle underlying the above argument?",
    "Which one of the following conclusions can be drawn from the above passage?",
    "Which one of the following is a conclusion that can be drawn from the above passage?",
    "Which one of the following conclusions is best supported by the data given above?"
]
//question types
export const questionTypesMath = [
    "Binary Operation Evaluation",
    "Inequality Solving",
    "Simultaneous Equations",
    "Geometry (Length Calculation)",
    "Geometry (Cube and Line Length)",
    "Geometry (Triangle Area)",
    "Sequence Analysis",
    "Integer Properties (Exponentiation)",
    "Quadratic Equations (Roots)",
    "Quadratic Equations (Roots Sum and Product)",
    "Quadratic Equations (Roots Difference)",
    "Right-Angled Triangle",
    "Simultaneous Equations (Solution Value)",
    "Permutations (Race Outcomes)",
    "Algebraic Simplification",
    "Algebraic Expression Comparison",
    "Geometry (Circle Quadrant and Shaded Area)",
    "Linear Equations (Line Equation)",
    "Inequality Analysis",
    "Integer Properties (Multiples)"
];
